/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bowling;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {

    public static void main(String[] args) {
        BowlingGame bowlingGame = new AmericanBowlingGame();
        bowlingGame.start(args);
        bowlingGame.showScoresPerFrame();
        log.info("Total Game Score is: {}", bowlingGame.getTotalGameScore());
    }
}
